-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2020-05-18 17:36:02 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE "Comment" (
    comment_id       INTEGER NOT NULL,
    comment_text     VARCHAR2(1000),
    duration_sec     INTEGER,
    datetime         TIMESTAMP,
    shape            VARCHAR2(15),
    event_event_id   INTEGER NOT NULL
);

ALTER TABLE "Comment" ADD CONSTRAINT comment_pk PRIMARY KEY ( comment_id );

CREATE TABLE country (
    country_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_name );

CREATE TABLE event (
    event_id          INTEGER NOT NULL,
    place_longitude   NUMBER(9, 6) NOT NULL,
    place_latitude    NUMBER(9, 6) NOT NULL
);

ALTER TABLE event ADD CONSTRAINT event_pk PRIMARY KEY ( event_id );

CREATE TABLE location (
    city_name              VARCHAR2(20) NOT NULL,
    country_country_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( city_name );

CREATE TABLE place (
    latitude             NUMBER(9, 6) NOT NULL,
    longitude            NUMBER(9, 6) NOT NULL,
    location_city_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE place ADD CONSTRAINT place_pk PRIMARY KEY ( longitude,
                                                        latitude );

ALTER TABLE "Comment"
    ADD CONSTRAINT comment_event_fk FOREIGN KEY ( event_event_id )
        REFERENCES event ( event_id );

ALTER TABLE event
    ADD CONSTRAINT event_place_fk FOREIGN KEY ( place_longitude,
                                                place_latitude )
        REFERENCES place ( longitude,
                           latitude );

ALTER TABLE location
    ADD CONSTRAINT location_country_fk FOREIGN KEY ( country_country_name )
        REFERENCES country ( country_name );

ALTER TABLE place
    ADD CONSTRAINT place_location_fk FOREIGN KEY ( location_city_name )
        REFERENCES location ( city_name );

ALTER TABLE "Comment"
    ADD CONSTRAINT comment_event_fk FOREIGN KEY ( event_event_id )
        REFERENCES event ( event_id );

ALTER TABLE event
    ADD CONSTRAINT event_place_fk FOREIGN KEY ( place_longitude,
                                                place_latitude )
        REFERENCES place ( longitude,
                           latitude );

ALTER TABLE location
    ADD CONSTRAINT location_country_fk FOREIGN KEY ( country_country_name )
        REFERENCES country ( country_name );

ALTER TABLE place
    ADD CONSTRAINT place_location_fk FOREIGN KEY ( location_city_name )
        REFERENCES location ( city_name );

